### PR TITLE
FIX worker-loader execution order.

### PR DESCRIPTION
**Pull request by cashewnuts**
Like https://github.com/zeit/next-plugins/issues/414#issuecomment-493320435 has said, if I do along with the readme, it shows 404 for every pages.
This fixes the above issue. And now, it seems everything works great.

### CODE REVIEW

**Comment by Poky85** [comment]
Works fine for me with Next 9.1.6

**Comment by Manc** [comment]
I tried a good few hours to get Web Workers with TypeScript and Next.js working, and the little tweak from this PR finally made it work.

I highly recommend that it will be merged and then a new version of the plugin is published.

**Comment by hyusetiawan** [comment]
any update on this?  cc @timneutkens

**Comment by ian97531** [comment]
This worked for me on Next 9.4.4 after being unable to get this plugin to work.

**Review by bendman — APPROVED** [review]

**Comment by timneutkens** [comment]
This plugin is no longer relevant as Next.js now supports `new Worker` through webpack 5. The worker example has been updated: https://github.com/vercel/next.js/blob/canary/examples/with-web-worker/pages/index.js#L6

**Pull request closed without merging**
