### PR TITLE
fix: upgrade style plugins for Webpack 4/5 compatibility

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
@timneutkens this repo is super out of date with what's on npm, so most of this is me copying out of node modules. mini-css needed upgrading to support

**Comment by kachkaev** [comment]
Aren’t `next-css` and `next-scss` deprecated following the [introduction](https://nextjs.org/blog/next-9-2#built-in-css-support-for-global-stylesheets) of [built-in CSS support ](https://nextjs.org/docs/basic-features/built-in-css-support) in Next? What makes you still want to use the plugins?

**Comment by ScriptedAlchemy** [comment]
To support importing .scss, .sass, .less, or .styl files you can use the following plugins:

@zeit/next-sass
@zeit/next-less
@zeit/next-stylus

Those still seem to come from the same repo. Depending on older copies of next-css

**Comment by ScriptedAlchemy** [comment]
Point me to where the code is internally. I’ll patch it there - but I didn’t see anything in next canary branch

**Pull request closed without merging**
