### PR TITLE
Added next-html as a community plugin

### PR DESCRIPTION
**Pull request by omeraplak**

### CODE REVIEW

**Comment by timneutkens** [comment]
What is the use case of this 🤔

**Comment by omeraplak** [comment]
The use case of this is importing raw html file on next.js project.

**Comment by kachkaev** [comment]
Also curious. Could you please share an example @omeraplak? What if I'm missing out by not using such a plugin? 😱

**Comment by omeraplak** [comment]
In my project, i need to render raw html. For exemple, EU GDPR contents are available in so many languages. But i do not want to convert all html files to JSX syntax. I added html files to my project and imported to react components

Example:

``
import * as En from './en.html';
import * as French from './fr.html';
import * as Spanish from './es.html';
....
....

public render(): JSX.Element {
	return (
		<div dangerouslySetInnerHTML={{__html: En}} />
	);
}

``
@kachkaev  @timneutkens

**Comment by timneutkens** [comment]
Hey! We're deprecating this repository hence why this PR hasn't been merged. I just updated the readme. You can try adding it to the community awesome list: https://github.com/unicodeveloper/awesome-nextjs.

**Pull request closed without merging**
